global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'fastapi-market'
    metrics_path: /metrics
    static_configs:
      - targets: ['market:8000']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']