apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: emarket
build:
  artifacts:
    - image: emarket
      context: ./Market
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    tryImportMissing: false
deploy:
  kubectl:
    manifests:
      - k8s/apps/eMarket/deployment.yaml
      - k8s/apps/eMarket/service.yaml
      - k8s/apps/eMarket/secrets.yaml
      
portForward:
  - resourceType: deployment
    resourceName: emarket
    port: 8000
    localPort: 8000