architecture: replicaset
replicaCount: 3

auth:
  enabled: true
  rootPassword: ""

  database: product_database

  usernames: ""
  passwords: ""

persistence:
  enabled: true
  size: 8Gi

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m
